create_clock -period 4 -name clk [get_ports clk]
# External MIG 7-Series DDR3 Memory Interface Constraint
set_property PACKAGE_PIN A15 [get_ports {ddr3_addr[15]}]
set_property IOSTANDARD SSTL15 [get_ports {ddr3_addr[15]}]

set_load 5.000 [all_outputs]
set_property LOAD 5 [get_ports done]
set_property LOAD 5 [get_ports load_done]
set_property LOAD 5 [get_ports {result[0]}]
set_property LOAD 5 [get_ports {result[10]}]
set_property LOAD 5 [get_ports {result[11]}]
set_property LOAD 5 [get_ports {result[12]}]
set_property LOAD 5 [get_ports {result[13]}]
set_property LOAD 5 [get_ports {result[14]}]
set_property LOAD 5 [get_ports {result[15]}]
set_property LOAD 5 [get_ports {result[16]}]
set_property LOAD 5 [get_ports {result[17]}]
set_property LOAD 5 [get_ports {result[18]}]
set_property LOAD 5 [get_ports {result[19]}]
set_property LOAD 5 [get_ports {result[1]}]
set_property LOAD 5 [get_ports {result[20]}]
set_property LOAD 5 [get_ports {result[21]}]
set_property LOAD 5 [get_ports {result[22]}]
set_property LOAD 5 [get_ports {result[23]}]
set_property LOAD 5 [get_ports {result[24]}]
set_property LOAD 5 [get_ports {result[25]}]
set_property LOAD 5 [get_ports {result[26]}]
set_property LOAD 5 [get_ports {result[27]}]
set_property LOAD 5 [get_ports {result[28]}]
set_property LOAD 5 [get_ports {result[29]}]
set_property LOAD 5 [get_ports {result[2]}]
set_property LOAD 5 [get_ports {result[30]}]
set_property LOAD 5 [get_ports {result[31]}]
set_property LOAD 5 [get_ports {result[3]}]
set_property LOAD 5 [get_ports {result[4]}]
set_property LOAD 5 [get_ports {result[5]}]
set_property LOAD 5 [get_ports {result[6]}]
set_property LOAD 5 [get_ports {result[7]}]
set_property LOAD 5 [get_ports {result[8]}]
set_property LOAD 5 [get_ports {result[9]}]
